# Generated by Django 2.1.5 on 2019-03-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(default='', editable=False, max_length=20, null=True, verbose_name='Room Name')),
                ('room_floor', models.CharField(default='', editable=False, max_length=20, null=True, verbose_name='Room floor')),
            ],
        ),
    ]
