# Generated by Django 2.1.5 on 2019-03-29 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occupy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='Time')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Room')),
            ],
        ),
    ]
