# Generated by Django 2.1.5 on 2019-04-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_occupy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_occur_time', models.DateTimeField(verbose_name='Error Cccur Time')),
                ('error_string', models.CharField(max_length=255, verbose_name='Error String')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255, verbose_name='User Name')),
                ('user_password', models.CharField(max_length=255, verbose_name='User Password')),
            ],
        ),
    ]
