# Generated by Django 2.2.4 on 2019-10-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floor4', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='roomType',
            field=models.CharField(default='S', max_length=6),
        ),
    ]
