# Generated by Django 2.1.5 on 2019-03-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.PositiveSmallIntegerField(verbose_name='room_id')),
                ('enter_time', models.DateTimeField(verbose_name='enter time')),
                ('leave_time', models.DateTimeField(verbose_name='leave time')),
            ],
        ),
    ]
