# Generated by Django 2.1.5 on 2019-03-29 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_monitor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
