# Generated by Django 2.2.6 on 2019-10-22 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('floor', '0001_initial'),
        ('timers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('roomID', models.CharField(max_length=5)),
                ('totalOccupants', models.IntegerField(default=0)),
                ('avgOccLength', models.IntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floor.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('roomID', models.CharField(max_length=5)),
                ('totalOccupants', models.IntegerField(default=0)),
                ('avgOccLength', models.IntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floor.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('roomID', models.CharField(max_length=5)),
                ('totalOccupants', models.IntegerField(default=0)),
                ('avgOccLength', models.IntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floor.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('roomID', models.CharField(max_length=5)),
                ('totalOccupants', models.IntegerField(default=0)),
                ('avgOccLength', models.IntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floor.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('roomID', models.CharField(max_length=5)),
                ('totalOccupants', models.IntegerField(default=0)),
                ('avgOccLength', models.IntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floor.Room')),
            ],
        ),
        migrations.DeleteModel(
            name='TimeFrame',
        ),
    ]
