# Generated by Django 2.2.4 on 2019-10-01 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OccupancyStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalOccupancy', models.IntegerField()),
                ('averageDayOccupancy', models.IntegerField()),
                ('averageWeekOccupancy', models.IntegerField()),
                ('averageMonthOccupancy', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomID', models.CharField(max_length=5)),
                ('occupied', models.IntegerField()),
                ('lastExited', models.DateTimeField(auto_now_add=True)),
                ('lastEntered', models.DateTimeField(auto_now_add=True)),
                ('roomType', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='RoomUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('largestHoursInRoom', models.IntegerField()),
                ('currentDate', models.DateTimeField(auto_now_add=True)),
                ('occupancyStats', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stats.OccupancyStats')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stats.Room')),
            ],
        ),
    ]
