# Generated by Django 2.2.1 on 2019-10-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomType',
            field=models.CharField(max_length=2),
        ),
    ]
