# Generated by Django 2.2.1 on 2019-10-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20191002_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupancystats',
            name='averageDayOccupancy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='occupancystats',
            name='averageMonthOccupancy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='occupancystats',
            name='averageWeekOccupancy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='occupancystats',
            name='totalOccupancy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='occupied',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='roomID',
            field=models.CharField(default='default', max_length=5),
        ),
        migrations.AlterField(
            model_name='room',
            name='roomType',
            field=models.CharField(default='S', max_length=2),
        ),
        migrations.AlterField(
            model_name='roomusage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
