# Generated by Django 2.2.1 on 2019-10-11 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('floor', '0001_initial'),
        ('stats', '0002_auto_20191008_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='statsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.IntegerField(default=0)),
                ('roomID', models.CharField(max_length=5)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('roomPointer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floor.Room')),
            ],
        ),
        migrations.RemoveField(
            model_name='roomusage',
            name='occupancyStats',
        ),
        migrations.RemoveField(
            model_name='roomusage',
            name='room',
        ),
        migrations.DeleteModel(
            name='OccupancyStats',
        ),
        migrations.DeleteModel(
            name='RoomUsage',
        ),
    ]
