# Generated by Django 2.2.6 on 2019-10-29 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20191011_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statslog',
            name='roomPointer',
        ),
    ]
