# Generated by Django 2.2.4 on 2019-10-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20191002_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomusage',
            name='largestHoursInRoom',
            field=models.IntegerField(default=0),
        ),
    ]
