# Generated by Django 2.2.6 on 2019-10-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_remove_statslog_roompointer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('roomID', models.CharField(max_length=5)),
                ('totalOccupants', models.IntegerField(default=0)),
                ('avgOccLength', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('roomID', models.CharField(max_length=5)),
                ('totalOccupants', models.IntegerField(default=0)),
                ('avgOccLength', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('roomID', models.CharField(max_length=5)),
                ('totalOccupants', models.IntegerField(default=0)),
                ('avgOccLength', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('roomID', models.CharField(max_length=5)),
                ('totalOccupants', models.IntegerField(default=0)),
                ('avgOccLength', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('roomID', models.CharField(max_length=5)),
                ('totalOccupants', models.IntegerField(default=0)),
                ('avgOccLength', models.IntegerField(default=0)),
            ],
        ),
    ]
