# Generated by Django 2.2.6 on 2019-11-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_day_hour_month_week_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hour',
        ),
        migrations.AlterField(
            model_name='day',
            name='avgOccLength',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='month',
            name='avgOccLength',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='week',
            name='avgOccLength',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='year',
            name='avgOccLength',
            field=models.DurationField(),
        ),
    ]
