# Generated by Django 2.2.1 on 2019-11-12 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_auto_20191105_1646'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Week',
        ),
    ]
