# Generated by Django 2.2.1 on 2019-12-06 21:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_delete_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statslog',
            name='timeStamp',
        ),
        migrations.AddField(
            model_name='statslog',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
