# Generated by Django 2.1.5 on 2019-08-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomID', models.IntegerField()),
                ('occupied', models.IntegerField()),
                ('lastExited', models.DateField()),
                ('lastEntered', models.DateField()),
            ],
        ),
    ]
