# Generated by Django 2.2.1 on 2019-08-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floor3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomID',
            field=models.CharField(max_length=5),
        ),
    ]
