# Generated by Django 2.2.4 on 2019-10-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floor3', '0002_auto_20190815_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='roomType',
            field=models.CharField(default='S', max_length=6),
        ),
    ]
